### ISSUE TITLE
what happend???

### ISSUE THREAD

**Issue by kingking888** [xvwvx/LookinLoader#1]
<img width="954" alt="image" src="https://github.com/xvwvx/LookinLoader/assets/44130236/cb75eea3-b3af-446d-afe3-77a50a98d1cc">

**Comment by xvwvx** [comment]
![image](https://github.com/xvwvx/LookinLoader/assets/11221451/2c93f75d-f96d-43d4-bedb-e0ade9bbe463)
你再看看，有点忘了
